trigger:
- main

pool:
  name: SelfHostedPool

variables:
- group: New variable group 05-Apr

steps:
- checkout: self

# 1. BUILD
- script: |
    cd board
    mvn clean package -DskipTests
  displayName: Build Java App

# 2. SONARQUBE
- script: |
    cd board
    mvn sonar:sonar \
      -Dsonar.projectKey=$(SONAR_PROJECT_KEY) \
      -Dsonar.host.url=$(SONAR_HOST_URL) \
      -Dsonar.login=$(SONAR_TOKEN)
  displayName: SonarQube Scan

# 3. DOCKER BUILD
- script: |
    docker build -t $(ACR_NAME).azurecr.io/$(IMAGE_NAME):$(Build.BuildId) ./board
  displayName: Docker Build

# 4. TRIVY SCAN - warn only, never blocks pipeline
- script: |
    trivy image --severity CRITICAL,HIGH \
      --exit-code 0 \
      $(ACR_NAME).azurecr.io/$(IMAGE_NAME):$(Build.BuildId)
  displayName: Trivy Security Scan

# 5. LOGIN TO ACR
- task: AzureCLI@2
  displayName: Login to ACR
  inputs:
    azureSubscription: 'azure-sc'
    scriptType: bash
    scriptLocation: inlineScript
    inlineScript: |
      az acr login --name $(ACR_NAME)

# 6. PUSH IMAGE
- script: |
    docker push $(ACR_NAME).azurecr.io/$(IMAGE_NAME):$(Build.BuildId)
  displayName: Push Image to ACR

# 7. CONNECT TO AKS
- task: AzureCLI@2
  displayName: Connect to AKS
  inputs:
    azureSubscription: 'azure-sc'
    scriptType: bash
    scriptLocation: inlineScript
    inlineScript: |
      az aks get-credentials \
        --resource-group gowtham-rg \
        --name $(AKS_CLUSTER) \
        --overwrite-existing

# 8. DEPLOY TO AKS
- script: |
    kubectl apply -f board/k8s/
    kubectl set image deployment/board-app \
      board-app=$(ACR_NAME).azurecr.io/$(IMAGE_NAME):$(Build.BuildId) \
      -n default
  displayName: Deploy to AKS