apiVersion: apps/v1
kind: Deployment
metadata:
  name: board-app
  labels:
    app: board-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: board-app
  template:
    metadata:
      labels:
        app: board-app
    spec:
      containers:
      - name: board-app
        image: prasadacr3dbbzl.azurecr.io/board-app:v1
        ports:
        - containerPort: 8080